/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/AboutSection.vue')['default']
    AppBanner: typeof import('./components/AppBanner.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CompaniesSection: typeof import('./components/CompaniesSection.vue')['default']
    MouseTrail: typeof import('./components/MouseTrail.vue')['default']
    MyAvatar: typeof import('./components/MyAvatar.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    ProjectsSection: typeof import('./components/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsSection: typeof import('./components/SkillsSection.vue')['default']
  }
}
